<!-- Contact Section with Modern Glass Split Layout -->
<div class="relative w-full overflow-hidden bg-black py-12 sm:py-20" use:revealOnScroll>
	<!-- Background Effects -->
	<div class="absolute inset-0">
		<div
			class="absolute left-10 top-20 h-96 w-96 animate-pulse rounded-full bg-gradient-to-r from-purple-600/30 to-pink-600/30 blur-3xl"
		></div>
		<div
			class="absolute bottom-10 right-20 h-80 w-80 animate-pulse rounded-full bg-gradient-to-r from-blue-600/20 to-purple-600/20 blur-3xl"
			style="animation-delay: 2s;"
		></div>
		<div
			class="absolute left-1/2 top-1/2 h-60 w-60 animate-pulse rounded-full bg-gradient-to-r from-pink-400/20 to-orange-400/20 blur-2xl"
			style="animation-delay: 4s;"
		></div>
		
		<!-- Floating Particles -->
		<div class="absolute inset-0">
			<div class="floating-particle absolute left-1/4 top-1/4 h-1 w-1 rounded-full bg-white/20"></div>
			<div class="floating-particle absolute right-1/3 top-1/3 h-1.5 w-1.5 rounded-full bg-pink-300/30" style="animation-delay: 1s;"></div>
			<div class="floating-particle absolute left-2/3 bottom-1/4 h-1 w-1 rounded-full bg-purple-300/30" style="animation-delay: 2s;"></div>
		</div>
	</div>

	<div class="container relative z-10 mx-auto px-4 sm:px-6 lg:px-8">
		<!-- Split Layout Container -->
		<div class="grid h-screen min-h-[600px] grid-cols-1 items-center gap-8 lg:grid-cols-2 lg:gap-16">
			
			<!-- Left Side - Title & Description -->
			<div class="flex flex-col justify-center space-y-8 lg:pl-8">
				<div class="reveal-up">
					<div class="relative">
						<h1 class="mb-6 text-5xl font-bold leading-tight text-white sm:text-6xl lg:text-7xl xl:text-8xl">
							Let's
							<br />
							<span class="bg-gradient-to-r from-pink-400 via-purple-400 to-blue-400 bg-clip-text text-transparent">
								Connect
							</span>
						</h1>
						
						<!-- Decorative Elements -->
						<div class="absolute -right-4 -top-2 h-3 w-3 animate-ping rounded-full bg-pink-400 opacity-75"></div>
						<div class="absolute -bottom-4 -left-2 h-2 w-2 animate-pulse rounded-full bg-purple-400"></div>
						<div class="absolute right-1/4 top-1/2 h-1.5 w-1.5 animate-bounce rounded-full bg-blue-400" style="animation-delay: 0.5s;"></div>
					</div>
				</div>
				
				<div class="reveal-up" style="animation-delay: 0.3s;">
					<p class="text-lg leading-relaxed text-gray-300 sm:text-xl lg:text-2xl">
						Ready to collaborate and build something extraordinary? Let's turn ideas into reality.
					</p>
					
					<div class="mt-8 flex flex-col gap-4 sm:flex-row">
						<a
							href="./contact"
							class="group relative transform overflow-hidden rounded-2xl bg-gradient-to-r from-pink-500 to-purple-500 px-8 py-4 font-bold text-black transition-all duration-300 hover:scale-105"
						>
							<div class="absolute inset-0 bg-gradient-to-r from-purple-500 to-pink-500 opacity-0 transition-opacity duration-300 group-hover:opacity-100"></div>
							<span class="relative flex items-center">
								Get in Touch
								<svg class="ml-2 h-5 w-5 transition-transform group-hover:translate-x-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
								</svg>
							</span>
						</a>
						
						<a
							href="#about"
							class="group rounded-2xl border border-pink-400/30 px-8 py-4 font-bold text-pink-300 backdrop-blur-sm transition-all duration-300 hover:border-pink-400/50 hover:bg-pink-400/10 hover:scale-105"
						>
							<span class="flex items-center">
								View My Work
								<svg class="ml-2 h-5 w-5 transition-transform group-hover:rotate-45" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/>
								</svg>
							</span>
						</a>
					</div>
				</div>
			</div>

			<!-- Right Side - Glass Cards Stack -->
			<div class="reveal-up flex items-center justify-center lg:pr-8" style="animation-delay: 0.6s;">
				<div class="toast-wrap relative h-[580px] w-full max-w-lg">
					<!-- Glass Background - bigger and more prominent -->
					<div class="absolute inset-4 rounded-3xl bg-gradient-to-br from-white/8 via-white/12 to-white/8 backdrop-blur-3xl shadow-2xl"></div>
					<div class="absolute inset-4 rounded-3xl bg-gradient-to-br from-pink-500/8 to-purple-500/8"></div>
					
					<!-- Toast Stack Container -->
					<div class="toast-list relative h-full w-full p-10">
						<!-- All cards will be generated by JavaScript -->
					</div>

					<!-- Navigation Dots -->
					<div class="absolute -bottom-6 left-1/2 flex -translate-x-1/2 space-x-3">
						<button type="button" class="nav-dot h-2.5 w-2.5 rounded-full bg-white/50 transition-all duration-300 hover:bg-white/80" data-index="0" aria-label="Show contact 1"></button>
						<button type="button" class="nav-dot h-2.5 w-2.5 rounded-full bg-white/50 transition-all duration-300 hover:bg-white/80" data-index="1" aria-label="Show contact 2"></button>
						<button type="button" class="nav-dot h-2.5 w-2.5 rounded-full bg-white/50 transition-all duration-300 hover:bg-white/80" data-index="2" aria-label="Show contact 3"></button>
						<button type="button" class="nav-dot h-2.5 w-2.5 rounded-full bg-white/50 transition-all duration-300 hover:bg-white/80" data-index="3" aria-label="Show contact 4"></button>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>

<style>
	.toast-wrap {
		perspective: 1000px;
	}

	.toast-list {
		transform-style: preserve-3d;
		position: relative;
	}

	/* Toast card base styles - bigger and solid */
	:global(.toast-card) {
		position: absolute;
		top: 40%;
		left: 50%;
		width: calc(100% - 5rem);
		height: 70%;
		border-radius: 24px;
		cursor: pointer;
		transition: all 0.6s cubic-bezier(0.23, 1, 0.32, 1);
		transform-origin: center center;
		border: 1px solid rgba(255, 255, 255, 0.15);
		box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
	}

	/* Better glass stack positioning - using percentage */
	:global(.toast-card:nth-child(1)) {
		transform: translateX(-50%) translateY(-50%) translateZ(0px) scale(1) rotateX(0deg);
		opacity: 1;
		z-index: 4;
	}

	:global(.toast-card:nth-child(2)) {
		transform: translateX(-50%) translateY(calc(-50% + 12%)) translateZ(-20px) scale(0.93) rotateX(4deg);
		opacity: 0.9;
		z-index: 3;
	}

	:global(.toast-card:nth-child(3)) {
		transform: translateX(-50%) translateY(calc(-50% + 24%)) translateZ(-40px) scale(0.86) rotateX(8deg);
		opacity: 0.75;
		z-index: 2;
	}

	:global(.toast-card:nth-child(4)) {
		transform: translateX(-50%) translateY(calc(-50% + 36%)) translateZ(-60px) scale(0.79) rotateX(12deg);
		opacity: 0.6;
		z-index: 1;
	}

	/* Glass card content styling */
	:global(.card-content) {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100%;
		padding: 1.5rem;
		border-radius: 20px;
		text-align: center;
		position: relative;
		overflow: hidden;
	}

	:global(.card-content::before) {
		content: '';
		position: absolute;
		inset: 0;
		background: linear-gradient(135deg, rgba(255,255,255,0.1) 0%, rgba(255,255,255,0.05) 100%);
		border-radius: 20px;
		transition: opacity 0.3s ease;
	}

	:global(.card-content:hover::before) {
		opacity: 0.7;
	}

	:global(.card-content:hover) {
		transform: translateY(-4px) scale(1.02);
		box-shadow: 0 12px 40px rgba(0, 0, 0, 0.4);
		border-color: rgba(255, 255, 255, 0.2);
	}

	/* Icon styling - bigger and more solid */
	:global(.contact-icon) {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 80px;
		height: 80px;
		border-radius: 20px;
		margin-bottom: 1.5rem;
		background: rgba(255, 255, 255, 0.15);
		backdrop-filter: blur(10px);
		transition: all 0.3s ease;
		border: 1px solid rgba(255, 255, 255, 0.15);
		box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
	}

	:global(.contact-icon:hover) {
		background: rgba(255, 255, 255, 0.22);
		transform: scale(1.05) rotate(3deg);
		border-color: rgba(255, 255, 255, 0.25);
		box-shadow: 0 6px 30px rgba(0, 0, 0, 0.3);
	}

	/* Navigation dots - bigger */
	.nav-dot.active {
		background-color: rgb(255 255 255 / 0.95);
		transform: scale(1.4);
	}

	/* Floating particles animation */
	.floating-particle {
		animation: float 6s ease-in-out infinite;
	}

	@keyframes float {
		0%, 100% { transform: translateY(0px) rotate(0deg); }
		25% { transform: translateY(-10px) rotate(90deg); }
		50% { transform: translateY(0px) rotate(180deg); }
		75% { transform: translateY(-5px) rotate(270deg); }
	}

	/* Responsive adjustments - keep it big */
	@media (max-width: 1024px) {
		.grid {
			grid-template-columns: 1fr;
			gap: 4rem;
			text-align: center;
		}
		
		.toast-wrap {
			max-width: 420px;
			height: 520px;
		}
		
		:global(.toast-card) {
			width: calc(100% - 1rem);
			height: 180px;
		}
	}

	@media (max-width: 768px) {
		.toast-wrap {
			max-width: 100%;
			height: 480px;
		}
		
		:global(.toast-card) {
			height: 160px;
		}
		
		:global(.card-content) {
			padding: 1.5rem 1rem;
		}
		
		:global(.contact-icon) {
			width: 70px;
			height: 70px;
			margin-bottom: 1.25rem;
		}
	}
</style>

<script lang="ts">
	import { onMount } from 'svelte';

	onMount(() => {
		// Contact data with solid colors instead of transparent gradients
		const contactData = [
			{
				name: 'Instagram',
				handle: '@vyovyo___',
				status: 'Active now',
				statusColor: 'bg-green-400',
				solidBg: 'linear-gradient(135deg, #ec4899, #f97316)',
				textColor: 'text-pink-100',
				icon: `<svg class="h-9 w-9 text-white" fill="currentColor" viewBox="0 0 24 24">
					<path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
				</svg>`
			},
			{
				name: 'Discord',
				handle: 'chulinx',
				status: 'Online',
				statusColor: 'bg-green-400',
				solidBg: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
				textColor: 'text-indigo-100',
				icon: `<svg class="h-9 w-9 text-white" fill="currentColor" viewBox="0 0 24 24">
					<path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419-.0002 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9554 2.4189-2.1568 2.4189Z"/>
				</svg>`
			},
			{
				name: 'Email',
				handle: 'jirameth.wa@email.com',
				status: 'Reply in 24h',
				statusColor: 'bg-yellow-400',
				solidBg: 'linear-gradient(135deg, #ef4444, #f97316)',
				textColor: 'text-red-100',
				icon: `<svg class="h-9 w-9 text-white" fill="currentColor" viewBox="0 0 24 24">
					<path d="M24 5.457v13.909c0 .904-.732 1.636-1.636 1.636h-3.819V11.73L12 16.64l-6.545-4.91v9.273H1.636A1.636 1.636 0 0 1 0 19.366V5.457c0-.904.732-1.636 1.636-1.636h.715l9.649 7.285 9.649-7.285h.715A1.636 1.636 0 0 1 24 5.457z"/>
				</svg>`
			},
			{
				name: 'GitHub',
				handle: '@chulinuwu',
				status: 'Active dev',
				statusColor: 'bg-green-400',
				solidBg: 'linear-gradient(135deg, #6b7280, #374151)',
				textColor: 'text-gray-100',
				icon: `<svg class="h-9 w-9 text-white" fill="currentColor" viewBox="0 0 24 24">
					<path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
				</svg>`
			}
		];

		const toastList = document.querySelector('.toast-list') as HTMLElement;
		const navDots = document.querySelectorAll('.nav-dot') as NodeListOf<HTMLElement>;
		let currentIndex = 0;
		let intervalId: number;

		// Create glass toast cards
		function createToastCards() {
			toastList.innerHTML = '';
			
			contactData.forEach((contact, index) => {
				const card = document.createElement('div');
				card.className = 'toast-card';
				card.innerHTML = `
					<div class="card-content" style="background: ${contact.solidBg};">
						
						<!-- Icon -->
						<div class="contact-icon">
							${contact.icon}
						</div>
						
						<!-- Content -->
						<div class="space-y-3">
							<h3 class="text-2xl font-bold text-white">${contact.name}</h3>
							<p class="${contact.textColor} text-base font-medium">${contact.handle}</p>
						</div>
						
						<!-- Status -->
						<div class="flex items-center justify-center space-x-2 mt-4">
							<div class="h-2.5 w-2.5 animate-pulse rounded-full ${contact.statusColor}"></div>
							<span class="text-sm ${contact.textColor} opacity-90 font-medium">${contact.status}</span>
						</div>
					</div>
				`;
				toastList.appendChild(card);
			});

			console.log('🎴 Created', contactData.length, 'glass toast cards');
		}

		// Enhanced shuffle with glassmorphism effect
		function rotateStack() {
			console.log('🔄 Rotating glass stack, current index:', currentIndex);
			
			const firstCard = toastList.firstElementChild as HTMLElement;
			if (firstCard) {
				// Enhanced glass shuffle animation
				firstCard.style.transition = 'all 0.9s cubic-bezier(0.34, 1.56, 0.64, 1)';
				firstCard.style.transform = 'translateX(-50%) translateY(-250%) scale(1.15) rotateZ(-20deg) rotateX(15deg)';
				firstCard.style.opacity = '0';
				firstCard.style.filter = 'blur(8px)';
				firstCard.style.zIndex = '10';
				
				setTimeout(() => {
					// Move and reset
					toastList.appendChild(firstCard);
					firstCard.style.transition = 'none';
					firstCard.style.transform = '';
					firstCard.style.opacity = '';
					firstCard.style.filter = '';
					firstCard.style.zIndex = '';
					
					// Force reflow
					firstCard.offsetHeight;
					
					// Re-enable transitions
					setTimeout(() => {
						firstCard.style.transition = '';
					}, 50);
					
					currentIndex = (currentIndex + 1) % contactData.length;
					
					// Update navigation dots
					navDots.forEach((dot, index) => {
						dot.classList.toggle('active', index === currentIndex);
					});
					
					console.log('✨ Glass stack rotated, new index:', currentIndex);
				}, 900);
			}
		}

		// Auto-rotate function
		function startAutoRotate() {
			console.log('🎠 Starting glass auto-rotate...');
			intervalId = window.setInterval(() => {
				rotateStack();
			}, 5000); // Slower for better glass effect appreciation
		}

		// Navigation dot clicks
		navDots.forEach((dot, index) => {
			dot.addEventListener('click', () => {
				const rotationsNeeded = (index - currentIndex + contactData.length) % contactData.length;
				
				if (rotationsNeeded === 0) return;
				
				window.clearInterval(intervalId);
				
				let rotations = 0;
				const rotateInterval = setInterval(() => {
					rotateStack();
					rotations++;
					
					if (rotations >= rotationsNeeded) {
						clearInterval(rotateInterval);
						setTimeout(startAutoRotate, 7000);
					}
				}, 1000);
			});
		});

		// Pause on hover
		const toastWrap = document.querySelector('.toast-wrap') as HTMLElement;
		if (toastWrap) {
			toastWrap.addEventListener('mouseenter', () => {
				console.log('⏸️ Pausing glass rotation');
				window.clearInterval(intervalId);
			});
			
			toastWrap.addEventListener('mouseleave', () => {
				console.log('▶️ Resuming glass rotation');
				setTimeout(startAutoRotate, 2500);
			});
		}

		// Initialize
		createToastCards();
		
		setTimeout(() => {
			navDots[0].classList.add('active');
			startAutoRotate();
		}, 2000);

		// Cleanup
		return () => {
			window.clearInterval(intervalId);
		};
	});

    function revealOnScroll(node: Element) {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting) {
                        entry.target.classList.add('reveal-up');
                        observer.unobserve(entry.target);
                    }
                });
            },
            { threshold: 0.1 }
        );

        observer.observe(node);

        return {
            destroy() {
                observer.unobserve(node);
            }
        };
    }
</script>